name: github-analytics
schedule: "@daily"
start_date: "2025-01-01"
catchup: false

metadata_push:
  bigquery: true

default_connections:
  google_cloud_platform: "bigquery-default"

variables:
  current_dataset:
    type: string
    default: "dev_gh_analytics"
  gcs_bucket_name:
    type: string
    default: "gh-dezoomcamp-raw-events"
